### ISSUE TITLE
Output Report: Format MultiLine Strings to Yaml Literal Style

### ISSUE THREAD

**Issue by gregberns** [gregberns/fcheck#9]
When fcheck runs a process which emits multi-line output, like logging or a stacktrace, it would be helpful to render the yaml with linebreaks inseead of `\n` within the string.

Yaml supports [block scalars](https://yaml-multiline.info/), specifically the 'literal' style, indicated by a pipe (|).

```
---
tests:
  - name: a
    commands:
      - type: complete
        ...
        stdout: "[INF] Starting...\n[DBG] Table name\n[INF] dbconfig = Data Source=db\n[DBG] Tables: filemaker_rolodex\n[DBG] Anon START[ERR] Faulted: Errors occurred (Count: 1) \nNone\n"
```

Which would convert the yaml report into something more readable:

```
---
tests:
  - name: a
    commands:
      - type: complete
        ...
        stdout: |
          [INF] Starting...
          [DBG] Table name
          [INF] dbconfig = Data Source=db
          [DBG] Tables: filemaker_rolodex\n[DBG] Anon START
          [ERR] Faulted: Errors occurred (Count: 1) 
          None
```

## Problem

fcheck is currently using [serde-yaml](https://github.com/dtolnay/serde-yaml) to serialize the yaml. That project is in turn using [yaml-rust](https://github.com/chyh1990/yaml-rust). There are serveral PRs out to yaml-rust to add support for block literals, but [yaml-rust has not been responsive to merging them in](https://github.com/dtolnay/serde-yaml/issues/174#issuecomment-738338596).

We could look at using a different serialization library.
